### PR TITLE
Updated plotting_positions to allow preserving order via kwarg

### PR DESCRIPTION
**Pull request by celestinjr**
I had a need to be able to control plotting properties of the scatter markers (color, marker, etc.).  There's probably a better solution in the long term, but for now this allows me to:
1. Utilize the library's normal behavior to generate the plot
2. Remove the scatter points:  `ax.collections[0].remove()`
3. Calculate the x, y scatter positions with order preserved: `x, y = plotting_positions(failures, preserve_order=True)`
4. Replot the points with additional controls: `[ax.scatter(x[i], y[i], color=color, marker=markers[i], s=markersize) for i, color in enumerate(colors)]`

Please consider for incorporation if you see value.  Note that the default behavior is unchanged.  Order is only preserved by passing the optional kwarg `preserve_order=True` to the `plotting_positions` function.

Thanks for sharing your work on this project.

Attached:
[Test File](https://github.com/MatthewReid854/reliability/files/6070131/test_plotting_positions_preserve_order.py.txt)

### CODE REVIEW

**Comment by MatthewReid854** [comment]
Can you provide an example in which you need to control properties of the scatter plot?
I'm confused why passing plotting kwargs to the scatter plot has anything to do with preserving the order of the points.
Are you trying to give each scatter point different properties and if so why?
Very thorough pull request by the way! Certainly the most thorough I've received so far.

**Comment by celestinjr** [comment]
I'm fitting distributions (typically LogNormal2P or Weibull)  to corrosion
data (i.e. corrosion rates and/or component thicknesses).  One of the
things this offers is the ability to identify individual corrosion zones,
but to do so one needs to be able to correlate individual scatter points
back to the original data set to identify trends.  For example it may be
that corrosion is more aggressive in certain component types, pipe sizes,
orientations, etc.  Being able to color, format, query, etc. by these
different categories allows for easier identification of these trends.

**Comment by MatthewReid854** [comment]
Couldn't you just replot the scatter points using the function plot_points and specify their unique properties there?
I could include the ability to turn off the scatter plot for probability plots so you aren't overlaying different markers.

**Comment by celestinjr** [comment]
plot_points uses plotting_positions internally.  plotting_positions sorts the failures and doesn’t return the new order, so there’s no way to keep track or determine which plot point corresponds to which failure, unless I’m overlooking something.  I do support making plotting of the scatter points optional as you suggested, which would prevent wasted effort plotting then removing them. I’d also suggest also incorporating the preserve_order kwarg into the plot_points function and then you can pass it to the internal plotting_positions call.

**Comment by celestinjr** [comment]
FYI, when I initially tested things with the order preserved, one or more of the fit tests were failing, so I assumed they required the data to be sorted.  I'm unable to reproduce that test failure now, even with preserve_order=True as the default, so you might consider removing the kwarg and always preserving order.  All tests seem to be passing, but any untested/future methods that require sorted x, y data would need to sort the data themselves.

**Comment by MatthewReid854** [comment]
I appreciate all your work in the pull request, but I have decided to approach this differently to achieve the same outcome.
My approach is:
- plotting_positions now preserves order always. No additional kwargs required. I did this by restoring the order using the sorted dataframe's index.
- all the probability plots now have the argument show_scatter_points which defaults to True. If set to False it will hide the scatter points.
- You can redraw your scatter points using plot_points which passes kwargs directly to plt.scatter. This works because plt.scatter accepts a list for color.

Why did I do it like this rather than just allowing the probability plot to accept more kwargs? Because the probability plot uses the color kwarg to make the line and the points the same color (if color is specified). This gets complicated if color is a list as it is not clear what color the line should be. I didn't want to introduce new kwargs for line_color and points_color into the probability plot, especially since probability plot is used by so many other functions that are expecting to just provide the color kwarg.

Regarding your initial comment about different markers; This won't yet work with a list for marker due to an [issue](https://stackoverflow.com/questions/52303660/iterating-markers-in-plots/52303895#52303895) in matplotlib.

I have git pushed these changes now so you can test it.
I'll leave this issue open for comments. Please let me know if it meets your needs and whether you have any other suggestions.

Here is some example test code that shows this implementation:

```
from reliability.Distributions import Weibull_Distribution
from reliability.Fitters import Fit_Weibull_2P
import matplotlib.pyplot as plt
from reliability.Probability_plotting import Weibull_probability_plot, plot_points, plotting_positions
import numpy as np

# generate the data in 3 groups
n1 = 15
dist1 = Weibull_Distribution(alpha=50, beta=3)
data1 = dist1.random_samples(n1)
color1 = ['red'] * n1

n2 = 20
dist2 = Weibull_Distribution(alpha=80, beta=5)
data2 = dist2.random_samples(n2)
color2 = ['blue'] * n2

n3 = 12
dist3 = Weibull_Distribution(alpha=120, beta=6)
data3 = dist3.random_samples(n3)
color3 = ['green'] * n3

# merge the groups of data and the list of colors
data = np.hstack([data1, data2, data3])
color = np.hstack([color1, color2, color3])

# fit the model and turn off the probability plot
fit = Fit_Weibull_2P(failures=data, show_probability_plot=False, print_results=False)

# create the probability plot and hide the scatter points
Weibull_probability_plot(failures=data, show_scatter_points=False)

# redraw the scatter points. kwargs are passed to plt.scatter so a list of color is accepted
plot_points(failures=data, color=color)

# if you want the legend to show the different colors then you need to replot some points in separate scatter plots
x, y = plotting_positions(failures=data)
plt.scatter(x[0], y[0], color=color[0], marker='.', label='component 1')
plt.scatter(x[n1], y[n1], color=color[n1], marker='.', label='component 2')
plt.scatter(x[n1 + n2], y[n1 + n2], color=color[n1 + n2], marker='.', label='component 3')
plt.legend()

plt.show()
```

Figure_1

**Comment by celestinjr** [comment]
Agree with this solution.  Thanks!

**Pull request closed without merging**
